### ISSUE TITLE
大佬牛逼，能否加一个鼠标中键按下拖动的整个画布的功能

### ISSUE THREAD

**Issue by monotone** [oorzc/vscode-mindmap#1]

**Comment by oorzc** [comment]
暂不考虑增加该操作哦
目前有2种方式可以拖拽
1.点击图标
<img width="563" alt="image" src="https://github.com/oorzc/vscode-mindmap/assets/24369905/61d417f7-b899-4508-90f4-f664e9ec02d4">
2.点击主题文字拖动
![2](https://github.com/oorzc/vscode-mindmap/assets/24369905/cd60518b-bc35-47bc-84d6-289fdf326f06)
