### ISSUE TITLE
打开xmind文件错误

### ISSUE THREAD

**Issue by Aries210** [oorzc/vscode-mindmap#2]
![QQ截图20240201163759](https://github.com/oorzc/vscode-mindmap/assets/61650941/95495e3a-0276-43ce-be9f-1c3ca9e97b69)

**Comment by oorzc** [comment]
可以上传一下你的文件我看下吗

**Comment by Aries210** [comment]
我创建的是一个空的xmind后缀的文件，我正打算用你开发的插件制作xmind流程图。空的km后缀的文件是可以正常打开的发自我的iPhone------------------ 原始邮件 ------------------发件人: 黑夜  ***@***.***>发送时间: 2024年2月1日 16:46收件人: oorzc/vscode-mindmap ***@***.***>抄送: Aries210 ***@***.***>, Author ***@***.***>主题: Re: [oorzc/vscode-mindmap] 打开xmind文件错误 (Issue #2)
可以上传一下你的文件我看下吗

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/oorzc/vscode-mindmap/issues/2#issuecomment-1920790782",
"url": "https://github.com/oorzc/vscode-mindmap/issues/2#issuecomment-1920790782",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Aries210** [comment]
我创建的是一个空的xmind后缀的文件，我正打算用你开发的插件制作xmind思维导图。空的km后缀的文件是可以正常打开的

**Comment by Aries210** [comment]
> 可以上传一下你的文件我看下吗

我创建的是一个空的xmind后缀的文件，我正打算用你开发的插件制作xmind思维导图。空的km后缀的文件是可以正常打开的

**Comment by oorzc** [comment]
> > 可以上传一下你的文件我看下吗
> 
> 我创建的是一个空的xmind后缀的文件，我正打算用你开发的插件制作xmind思维导图，但是打开空的xmind文件时报错，空的km后缀的文件是可以正常打开的

好的，我空了修复下

**Comment by oorzc** [comment]
最新版v1.0.3，已修复
